/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertBanner: typeof import('./src/components/AlertBanner.vue')['default']
    ConflictResolveDialog: typeof import('./src/components/ConflictResolveDialog.vue')['default']
    CreateShareDialog: typeof import('./src/components/share/CreateShareDialog.vue')['default']
    FileCard: typeof import('./src/components/file/FileCard.vue')['default']
    FileContextMenu: typeof import('./src/components/file/FileContextMenu.vue')['default']
    FilePreviewDialog: typeof import('./src/components/file/FilePreviewDialog.vue')['default']
    FileRenameDialog: typeof import('./src/components/file/FileRenameDialog.vue')['default']
    FileTagEditor: typeof import('./src/components/FileTagEditor.vue')['default']
    FileTypeIcon: typeof import('./src/components/FileTypeIcon.vue')['default']
    FolderBreadcrumb: typeof import('./src/components/folder/FolderBreadcrumb.vue')['default']
    FolderCard: typeof import('./src/components/file/FolderCard.vue')['default']
    FolderCreateDialog: typeof import('./src/components/folder/FolderCreateDialog.vue')['default']
    FolderMoveDialog: typeof import('./src/components/folder/FolderMoveDialog.vue')['default']
    FolderRenameDialog: typeof import('./src/components/folder/FolderRenameDialog.vue')['default']
    FolderTree: typeof import('./src/components/folder/FolderTree.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./src/components/SideNav.vue')['default']
    TagManager: typeof import('./src/components/TagManager.vue')['default']
    TAlert: typeof import('tdesign-vue-next')['Alert']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TDescriptions: typeof import('tdesign-vue-next')['Descriptions']
    TDescriptionsItem: typeof import('tdesign-vue-next')['DescriptionsItem']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TDrawer: typeof import('tdesign-vue-next')['Drawer']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    ThumbnailImg: typeof import('./src/components/ThumbnailImg.vue')['default']
    TIcon: typeof import('./src/components/TIcon.vue')['default']
    TInput: typeof import('tdesign-vue-next')['Input']
    TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TOption: typeof import('tdesign-vue-next')['Option']
    TPagination: typeof import('tdesign-vue-next')['Pagination']
    TPopconfirm: typeof import('tdesign-vue-next')['Popconfirm']
    TProgress: typeof import('tdesign-vue-next')['Progress']
    TRadio: typeof import('tdesign-vue-next')['Radio']
    TRadioButton: typeof import('tdesign-vue-next')['RadioButton']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    TTable: typeof import('tdesign-vue-next')['Table']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    TTag: typeof import('tdesign-vue-next')['Tag']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
    TTree: typeof import('tdesign-vue-next')['Tree']
    UploadModal: typeof import('./src/components/UploadModal.vue')['default']
    UploadProgressIndicator: typeof import('./src/components/UploadProgressIndicator.vue')['default']
  }
}
