module.exports = {
  preset: 'ts-jest',
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '.',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/**/*.(t|j)s',
    '!src/main.ts',
    '!src/**/*.module.ts',
    '!src/**/*.controller.ts',
    '!src/**/*.dto.ts',
    '!src/**/*.gateway.ts',
    '!src/**/*.strategy.ts',
    '!src/**/*.entity.ts',
    '!src/migrations/**',
    '!src/**/__mocks__/**',
    '!src/common/filters/**',
    '!src/common/guards/**',
    '!src/common/interceptors/**',
    '!src/common/middleware/**',
    '!src/common/entities/**',
    '!src/common/constants/**',
    '!src/common/decorators/**',
    '!src/common/pipes/**',
    '!src/common/utils/**',
    '!src/common/file-logger.ts',
    '!src/jobs/**',
    '!src/database/**',
    '!src/config/**',
    // 以下模块不在本次核心业务路径测试范围内
    '!src/folder/**',
    '!src/tag/**',
    '!src/tasks/**',
    '!src/telemetry/**',
    '!src/user/**',
    '!src/alert/**',
    '!src/security/**',
    '!src/mailer/**',
    '!src/telegram/**',
    // 以下为依赖服务，非本次测试目标
    '!src/common/services/**',
    '!src/share/share-password.service.ts',
    '!src/file/chunk-upload.service.ts',
    '!src/file/thumbnail-crypto.service.ts',
    '!src/file/file-cache.service.ts',
    '!src/file/upload-job.service.ts',
    '!src/admin/dashboard.service.ts',
    '!src/admin/export.service.ts',
  ],
  coverageDirectory: './coverage',
  coverageThreshold: {
    global: {
      branches: 30,
      functions: 30,
      lines: 30,
      statements: 30,
    },
  },
  testEnvironment: 'node',
  testPathIgnorePatterns: ['/node_modules/', '/dist/'],
  moduleNameMapper: {
    '^src/(.*)$': '<rootDir>/src/$1',
    '^file-type$': '<rootDir>/src/__mocks__/file-type.ts',
  },
};
