import { createAlertRules, getAlertRuleMetadata } from './alert.rules';

describe('alert rules',()=>{
 const low:any={totalRequests:0,qpsAvg:0,error5xxCount:0,error4xxCount:0,totalBandwidth:0,p95Duration:0,uniqueIps:0};
 it('loads all rules concurrently and evaluates both sides of every condition',async()=>{const cache:any={get:jest.fn((_k:string,d:string)=>Promise.resolve(d))}; const rules=await createAlertRules(cache); expect(rules).toHaveLength(24); expect(cache.get).toHaveBeenCalledTimes(12); const high:any={totalRequests:1000,qpsAvg:400,error5xxCount:200,error4xxCount:300,totalBandwidth:101*60*1024*1024,p95Duration:0,uniqueIps:0}; for(const r of rules){expect(await r.evaluate(low)).toBeNull(); // SEC_/BOT_/MIRROR_/RELAY_/LARGE_FILE_/REPLICATION_ 为状态驱动规则：evaluate 恒为 null，由处理器、账号池、镜像或扩散观测采集触发
  if(!r.id.startsWith('SEC_')&&!r.id.startsWith('BOT_')&&!r.id.startsWith('MIRROR_')&&!r.id.startsWith('RELAY_')&&!r.id.startsWith('LARGE_FILE_')&&!r.id.startsWith('REPLICATION_')) expect(await r.evaluate(high)).toEqual(expect.any(String));} expect(getAlertRuleMetadata()).toHaveLength(24)});
 it('uses configured thresholds and falls back for invalid numbers',async()=>{const cache:any={get:jest.fn((_k:string,d:string)=>Promise.resolve(d==='100'?'invalid':'1'))}; const rules=await createAlertRules(cache); const qps=rules.find(r=>r.id==='TRAFFIC_QPS')!; expect(qps.cooldownMinutes).toBe(1); expect(await qps.evaluate({...low,qpsAvg:101,totalRequests:1})).toContain('101.0')});
 it('covers zero-request guard and security no-op evaluators',async()=>{const cache:any={get:jest.fn((_k:string,d:string)=>Promise.resolve(d))}; const rules=await createAlertRules(cache); const rate=rules.find(r=>r.id==='ERROR_5XX_RATE')!; expect(await rate.evaluate({...low,totalRequests:0,error5xxCount:999})).toBeNull(); for(const id of ['SEC_IP_FLOOD','SEC_BRUTE_FORCE','SEC_ABNORMAL_DOWNLOAD','BOT_POOL_ALL_UNAVAILABLE','BOT_POOL_FALLBACK_RATE','BOT_REPLY_FAILING','RELAY_NOT_READY','RELAY_FAILURE_BURST','RELAY_CLAIM_TIMEOUT_BURST','LARGE_FILE_COVERAGE_DEGRADED','REPLICATION_OBSERVABILITY_GAP']) expect(await rules.find(r=>r.id===id)!.evaluate(low)).toBeNull()});
 it('不再声明策略 A 专用的副本扩散规则（已由 RELAY_* 取代）',async()=>{const cache:any={get:jest.fn((_k:string,d:string)=>Promise.resolve(d))}; const rules=await createAlertRules(cache); expect(rules.find(r=>r.id==='BOT_POOL_REPLICATION_FAILING')).toBeUndefined(); expect(getAlertRuleMetadata().find(r=>r.id==='BOT_POOL_REPLICATION_FAILING')).toBeUndefined()});
});
